universe = vanilla
executable = /usr/local/bin/plot_posterior_corner.py
arguments = " --parameter m1 --parameter m2 "
getenv = True
request_disk = 10M
log = /home/georgy/ET/rift/.travis/ILE-GPU-Paper/demos/test_workflow_batch_gpu_lowlatency/iteration_$(macroiteration)_plot/logs/test-$(cluster)-$(process).log
error = /home/georgy/ET/rift/.travis/ILE-GPU-Paper/demos/test_workflow_batch_gpu_lowlatency/iteration_$(macroiteration)_plot/logs/test-$(cluster)-$(process).err
output = /home/georgy/ET/rift/.travis/ILE-GPU-Paper/demos/test_workflow_batch_gpu_lowlatency/iteration_$(macroiteration)_plot/logs/test-$(cluster)-$(process).out
notification = never
queue 1
