universe = vanilla
executable = /usr/local/bin/convergence_test_samples.py
arguments = " --always-succeed --method lame --parameter m1 --samples /home/georgy/ET/rift/.travis/ILE-GPU-Paper/demos/test_workflow_batch_gpu_lowlatency/posterior_samples-$(macroiteration).dat --samples /home/georgy/ET/rift/.travis/ILE-GPU-Paper/demos/test_workflow_batch_gpu_lowlatency/posterior_samples-$(macroiterationlast).dat "
getenv = True
requirements = 
initialdir = /home/georgy/ET/rift/.travis/ILE-GPU-Paper/demos/test_workflow_batch_gpu_lowlatency/iteration_$(macroiteration)_test
request_disk = 10M
log = /home/georgy/ET/rift/.travis/ILE-GPU-Paper/demos/test_workflow_batch_gpu_lowlatency/iteration_$(macroiteration)_test/logs/test-$(cluster)-$(process).log
error = /home/georgy/ET/rift/.travis/ILE-GPU-Paper/demos/test_workflow_batch_gpu_lowlatency/iteration_$(macroiteration)_test/logs/test-$(cluster)-$(process).err
output = /home/georgy/ET/rift/.travis/ILE-GPU-Paper/demos/test_workflow_batch_gpu_lowlatency/iteration_$(macroiteration)_test/logs/test-$(cluster)-$(process).out
notification = never
queue 1
