universe = vanilla
executable =  /home/georgy/ET/rift/.travis/ILE-GPU-Paper/demos/test_workflow_batch_gpu_lowlatency/unify.sh
getenv = True
requirements = 
periodic_remove = JobStatus =?= 2 && (CurrentTime - JobStartDate) > ( 3600)
initialdir = /home/georgy/ET/rift/.travis/ILE-GPU-Paper/demos/test_workflow_batch_gpu_lowlatency
request_disk = 10M
log = /home/georgy/ET/rift/.travis/ILE-GPU-Paper/demos/test_workflow_batch_gpu_lowlatency/iteration_$(macroiteration)_con/logs/unify-$(cluster)-$(process).log
error = /home/georgy/ET/rift/.travis/ILE-GPU-Paper/demos/test_workflow_batch_gpu_lowlatency/iteration_$(macroiteration)_con/logs/unify-$(cluster)-$(process).err
output = /home/georgy/ET/rift/.travis/ILE-GPU-Paper/demos/test_workflow_batch_gpu_lowlatency/all.net
notification = never
queue 1
